export enum MessageTemplate {
    OTP_VERIFICATION_CODE = "OTP_VERIFICATION_CODE",
    YSM_ONBOARDING_MESSAGE  = "YSM_ONBOARDING_MESSAGE",
    BIRTHDAY_WISHES_YSM     = "BIRTHDAY_WISHES_YSM",
    FEEDBACK_COLLECTION_MESSAGE     = "FEEDBACK_COLLECTION_MESSAGE",
    THANK_YOU_FOR_ATTENDING_WORKSHOP    = "THANK_YOU_FOR_ATTENDING_WORKSHOP",
    CERTIFICATE_ISSUED      = "CERTIFICATE_ISSUED",
    WORKSHOP_OR_INTERNSHIP_COMPLETION_MESSAGE   = "WORKSHOP_OR_INTERNSHIP_COMPLETION_MESSAGE",
    INTERNSHIP_REGISTRATION_CONFIRMATION    = "INTERNSHIP_REGISTRATION_CONFIRMATION",
    REGISTRATION_SUCCESSFUL     = "REGISTRATION_SUCCESSFUL",
    WORKSHOP_REMINDER_MESSAGE   = "WORKSHOP_REMINDER_MESSAGE",
}